[package]
name = "go-gen"
authors = ["Christoph Otter <chris@confio.gmbh>"]
version = "0.1.0"
edition = "2021"
publish = false

[package.metadata.release]
release = false

[dependencies]
cosmwasm-std = { version = "2.2.0-rc.4", path = "../std", features = [
    "cosmwasm_2_2",
    "staking",
    "stargate",
] }
cosmwasm-schema = { version = "2.2.0-rc.4", path = "../schema" }
anyhow = "1"
Inflector = "0.11.4"
indenter = "0.3.3"
schemars = { workspace = true }
